// Re-export SudokuEngine types
export type { CellColor, CandidateColor, Digit } from '@/lib/SudokuEngine';
export type {
  CellPosition,
  Candidate,
  Cell,
  LinkEndpoint,
  Link,
  SuperLinkEndpoint,
  SuperLink,
  SudokuSchema,
} from '@/lib/SudokuEngine';

export {
  getBoxIndex,
  getBoxRange,
  isInBox,
  getRelatedRange,
  isInSameUnit,
  createLink,
  getCell,
  isValidEndpoint,
  checkWeakLink,
  checkStrongLink,
  setCellInplace as setDigit,
  cloneCells,
  lastDigitRow,
  lastDigitCol,
  lastDigitBox,
  nakedPair,
  nakedPairsRow,
  hiddenPairsRow,
  nakedPairsCol,
  hiddenPairsCol,
  nakedPairsBox,
  hiddenPairsBox,
  setGroupCandidatesRow,
  checkGroupCandidatesRow,
  setGroupCandidatesCol,
  checkGroupCandidatesCol,
  setGroupCandidatesBox,
  checkGroupCandidatesBox,
  clearAllHighlighted,
  setHighlightedDigit,
  addHighlightedDigit,
  subHighlightedDigit,
  setHighlightedDigits,
  addHighlightedDigits,
  subHighlightedDigits,
  setHighlightedRow,
  addHighlightedRow,
  subHighlightedRow,
  setHighlightedRows,
  addHighlightedRows,
  subHighlightedRows,
  setHighlightedCol,
  addHighlightedCol,
  subHighlightedCol,
  setHighlightedCols,
  addHighlightedCols,
  subHighlightedCols,
  setHighlightedBox,
  addHighlightedBox,
  subHighlightedBox,
  setHighlightedBoxes,
  addHighlightedBoxes,
  subHighlightedBoxes,
  setHighlightedXY,
  addHighlightedXY,
  clearAllSelected,
  setSelectedDigit,
  addSelectedDigit,
  subSelectedDigit,
  setSelectedDigits,
  addSelectedDigits,
  subSelectedDigits,
  setSelectedCell,
  addSelectedCell,
  subSelectedCell,
  setSelectedCells,
  addSelectedCells,
  subSelectedCells,
  setSelectedRow,
  addSelectedRow,
  subSelectedRow,
  setSelectedRows,
  addSelectedRows,
  subSelectedRows,
  setSelectedCol,
  addSelectedCol,
  subSelectedCol,
  setSelectedCols,
  addSelectedCols,
  subSelectedCols,
  setSelectedBox,
  addSelectedBox,
  subSelectedBox,
  setSelectedBoxes,
  addSelectedBoxes,
  subSelectedBoxes,
  addCellColor,
  addCandidateColor,
  addCandidate,
  addCandidates,
  subCandidate,
  subCandidates,
} from '@/lib/SudokuEngine';

// Helper types for UI
import type { CellColor, CandidateColor, Digit } from '@/lib/SudokuEngine';

export type CellIndex = `${number}-${number}`;

export const getCellIndex = (row: number, col: number): CellIndex => `${row}-${col}`;

export const parseCellIndex = (index: CellIndex): { row: number; col: number } => {
  const [row, col] = index.split('-').map(Number);
  return { row, col };
};

// 示例数独题目
export const examplePuzzle: (Digit | null)[][] = [
  [5, 3, null, null, 7, null, null, null, null],
  [6, null, null, 1, 9, 5, null, null, null],
  [null, 9, 8, null, null, null, null, 6, null],
  [8, null, null, null, 6, null, null, null, 3],
  [4, null, null, 8, null, 3, null, null, 1],
  [7, null, null, null, 2, null, null, null, 6],
  [null, 6, null, null, null, null, 2, 8, null],
  [null, null, null, 4, 1, 9, null, null, 5],
  [null, null, null, null, 8, null, null, 7, 9],
];
